### ISSUE TITLE
Zvláštní chyba - cache

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/Hlidac-Statu#115]
Sice nevím, kde konkrétně tahle chyba vznikla (měli jsme ji v error logu), ale přijde mi z ní zvláštní následující kousek:

`5al8wFpU\Fg3mU1GmO2F9A==`
vs
`5al8wFpU/Fg3mU1GmO2F9A==`

Je tam otočené lomítko. Vypadá to, jako by se občas stalo, že ten hash, který leze sem do key `public void Insert(string key, byte[] value, TimeSpan expiration)` obsahoval `/`.

```
2021-09-13 06:25:21,798 [2318] ERROR : V20.BinaryFillCacheProvider error saving into \\dm3\data.Hlidacsmluv.cz\FileCache\E5\5al8wFpU/Fg3mU1GmO2F9A==.filecache
  | {cache key=(null), objectType=(null), log4net:HostName=webserver, log4net:UserName=DEVMASTERS\iishlidacsmluv, log4net:Identity=} | 
System.IO.DirectoryNotFoundException: Could not find a part of the path '\\dm3\data.Hlidacsmluv.cz\FileCache\E5\5al8wFpU\Fg3mU1GmO2F9A==.filecache'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at Devmasters.Cache.File.BinaryFileCacheProvider.Insert(String key, Byte[] value, TimeSpan expiration)
```

**Comment by suchoss** [comment]
Pokud je to Base64, tak `/` nemusí být jediný problém. Viz https://stackoverflow.com/a/13195228/2972326

**Comment by suchoss** [comment]
fixnuto v devmasters
