### ISSUE TITLE
Zajimava chyba ve vazbach

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/Hlidac-Statu#116]
Nevím co to způsobuje (lokálně to nedokážu zopakovat), ale máme v logách celkem často následující chybu:

```
2021-09-13 07:40:48,566 [3225] ERROR : 500 - Server error on /Osoba/Vazby/vladimir-michalcak-2

Url: GET https://www.hlidacstatu.cz/Osoba/Vazby/vladimir-michalcak-2?aktualnost=Nedavny

Exception:
  Ex Type: System.ArgumentException
  LogMessage: To and From properties should be same with merged Edge
  In Method: MergedEdge MergeWith(Edge)
  Stack Trace: 
   at HlidacStatu.Datastructures.Graphs.Graph.MergedEdge.MergeWith(Edge e) in P:\CCD\hs.team\Hlidac-Statu\Datastructures\Graphs\Graph.MergedEdge.cs:line 81
   at HlidacStatu.Datastructures.Graphs.Graph.Edge.MergeSameEdges(IEnumerable`1 edges) in P:\CCD\hs.team\Hlidac-Statu\Datastructures\Graphs\Graph.Edge.cs:line 304
   at HlidacStatu.Repositories.Graph.<>c.<PrintFlatRelations>b__21_2(<>f__AnonymousType7`2 k, IEnumerable`1 v) in P:\CCD\hs.team\Hlidac-Statu\Repositories\Graphs\Graph.cs:line 877
   at System.Linq.Lookup`2.ToArray[TResult](Func`3 resultSelector)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at HlidacStatu.Repositories.Graph.PrintFlatRelations(MergedEdge parent, Int32 level, IEnumerable`1 relations, TiskEnum typ, List`1 renderedIds, Boolean withStats, String highlightSubjId) in P:\CCD\hs.team\Hlidac-Statu\Repositories\Graphs\Graph.cs:line 862
   at HlidacStatu.Repositories.Graph.TiskVazeb(String rootName, IEnumerable`1 vazby, TiskEnum typ, Boolean withStats) in P:\CCD\hs.team\Hlidac-Statu\Repositories\Graphs\Graph.cs:line 834
   at AspNetCore.Views_Osoba_Vazby.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Osoba__osobaLayout.<ExecuteAsync>b__24_6() in P:\CCD\hs.team\Hlidac-Statu\Web\Views\Osoba\_osobaLayout.cshtml:line 149
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelper.ProcessContentAsync(TagHelperOutput output)
   at Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelper.CreateCacheEntry(CacheTagKey cacheKey, TagHelperOutput output)
   at Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Osoba__osobaLayout.ExecuteAsync() in P:\CCD\hs.team\Hlidac-Statu\Web\Views\Osoba\_osobaLayout.cshtml:line 148
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at HlidacStatu.Web.Startup.<>c.<<Configure>b__9_1>d.MoveNext() in P:\CCD\hs.team\Hlidac-Statu\Web\Startup.cs:line 188
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at HlidacStatu.LibCore.MiddleWares.OnHTTPErrorMiddleware.Invoke(HttpContext httpContext) in P:\CCD\hs.team\Hlidac-Statu\LibCore\MiddleWares\OnHTTPErrorMiddleware.cs:line 80



HTTP Headers:
   Accept: */*
   Accept-Encoding: gzip, deflate
   Cache-Control: no-cache
   Connection: Keep-Alive
   From: bingbot(at)microsoft.com
   Host: www.hlidacstatu.cz
   Pragma: no-cache
   User-Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
```

⚠Ale u té příležitosti bych rád poprosil o odstranění tohohle kódu:
```
if (num != 0 && Debugger.IsAttached)
        Debugger.Break();
```
v Devmasters.DT.Util (+- řádek 896 po dekompilaci) - privátní metoda _isContinuingIntervals.

Protože mě strašně vytáčí, že se mi na tom zasekne několikrát za sebou debugger, aniž bych chtěl tohle debugovat...

**Comment by suchoss** [comment]
Po dnešním debugování jiné "mizející" zvláštnosti, bych to tipoval na vadnou cache

**Comment by suchoss** [comment]
Tak cache to není, ale je to problém s vykreslováním slučováním hran grafu.

Snažíme se sloučit zjednodušeně následující vazbu:
```
p =[2020]=> c23
p =[2021]=> c23
```

což není plně slučitelné, protože tam jsou mezery.
