### ISSUE TITLE
Zajimava chyba v zebricku kindexu

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/Hlidac-Statu#118]
https://www.hlidacstatu.cz/kindex/zebricek/nejhorsi?rok=2019&kraj=&group=

```
LogMessage: The given key '26496224' was not present in the dictionary.
  In Method: Void ThrowKeyNotFoundException[T](T)
  Stack Trace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HlidacStatu.Lib.Analysis.KorupcniRiziko.Statistics.<>c.<Filter>b__38_3(ValueTuple`3 m) in P:\CCD\hs.team\Hlidac-Statu\Repositories\Analysis\KorupcniRiziko\Statistics.cs:line 119
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray(Int32 minIdx, Int32 maxIdx)
   at System.Linq.OrderedPartition`1.ToArray()
   at AspNetCore.Views_Kindex_Partials_Zebricek_child.ExecuteAsync() in P:\CCD\hs.team\Hlidac-Statu\Web\Views\Kindex\Partials\Zebricek_child.cshtml:line 15
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Kindex_Zebricek.<>c__DisplayClass11_0.<<ExecuteAsync>b__1>d.MoveNext() in P:\CCD\hs.team\Hlidac-Statu\Web\Views\Kindex\Zebricek.cshtml:line 148
```

**Comment by suchoss** [comment]
Lokálně nedokážu chybu reprodukovat :(

**Comment by suchoss** [comment]
Byl to problém s filecache..
