### ISSUE TITLE
Better Exception handling in API

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#140]
with call parameters and auth user…

Better than current 

```
webserver :: ERROR :: Dataset API

Logger: HlidacStatu
Thread: 86402
Date: 2021-10-16 09:02:35,050
NDC: {log4net:HostName=webserver, log4net:UserName=DEVMASTERS\iishlidacsmluv, log4net:Identity=} 

System.ArgumentException: The parameter: id to the url is null or empty
  at Elasticsearch.Net.ElasticsearchUrlFormatter.Format(String format, Object arg, IFormatProvider formatProvider)
  at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
  at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
  at System.String.Format(IFormatProvider provider, String format, Object[] args)
  at Elasticsearch.Net.ElasticLowLevelClient.Index[TResponse](String index, String id, PostData body, IndexRequestParameters requestParameters)
  at HlidacStatu.Datasets.DataSet.AddData(String data, String id, String createdBy, Boolean validateSchema, Boolean skipOCR, Boolean skipallowWriteAccess) in P:\CCD\hs.team\Hlidac-Statu\Datasets\DataSet.cs:line 622
  at HlidacStatu.Web.Controllers.ApiV2DatasetyController.DatasetItem_Update(String datasetId, String itemId, Object data, String mode) in P:\CCD\hs.team\Hlidac-Statu\Web\Controllers\ApiV2\ApiV2DatasetyControler.cs:line 372
```

**Comment by suchoss** [comment]
Done
