### ISSUE TITLE
To  parameter was not found in vertices

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#142]
webserver :: ERROR :: Vazby ERROR for tomas-svoboda-1

System.Exception: To parameter was not found in vertices
  at HlidacStatu.Datastructures.Graphs2.UnweightedGraph.ShortestPath(IVertex from, IVertex to) in P:\CCD\hs.team\Hlidac-Statu\Datastructures\Graphs2\UnweightedGraph.cs:line 60
  at HlidacStatu.Repositories.OsobaVazbyRepo._vazbyProICO(Osoba osoba, String ico) in P:\CCD\hs.team\Hlidac-Statu\Repositories\OsobaVazbyRepo.cs:line 161

**Comment by suchoss** [comment]
Dělalo to u neexistujících vazeb. Kód je už "opravený", aby to neházelo chyby
