### ISSUE TITLE
BlurredPageMinion Server Error shazuje container

### ISSUE THREAD

**Issue by jakubboucek** [HlidacStatu/Hlidac-Statu#203]
V tuto chvíli nelze `BlurredPageMinion` spustit, protože zřejmě server odpovídá chybou 500 Server Error. Protože container v důsledku této chyby spadne, není možné ponechat jej v běhu a čekat, až bude server opraven. 

🙏 pls resolve issue to indicate server error fixed.

```
fail: BlurredPageMinion.Worker[0]
      cannot read JSON from API. API error 500
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at BlurredPageMinion.Worker.ProcessTask() in C:\Projects\HlidacStatu.GitHub\Hlidac-Statu\Docker\BlurredPageMinion\Worker.cs:line 66
fail: BlurredPageMinion.Worker[0]
      System.NullReferenceException: Object reference not set to an instance of an object.
         at BlurredPageMinion.Worker.ProcessTask() in C:\Projects\HlidacStatu.GitHub\Hlidac-Statu\Docker\BlurredPageMinion\Worker.cs:line 156
```

**Comment by jakubboucek** [comment]
Opraveno, již funkční.
