### ISSUE TITLE
BlurredPageMinion: UnhandledException

### ISSUE THREAD

**Issue by radeksimko** [HlidacStatu/Hlidac-Statu#207]
Zkoušel jsem pustit BlurredPage miniona na M1 (darwin / arm64) [dle instrukcí](https://github.com/HlidacStatu/Hlidac-Statu/tree/main/Docker/BlurredPageMinion#jak-blurredpageminion-spustit):

```
Top level UnhandledException (1.3.2.0).System.IO.IOException
Top level UnhandledException (1.3.2.0).System.IO.IOException
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Projects\HlidacStatu.GitHub\Hlidac-Statu\Docker\BlurredPageMinion\Program.cs:line 34
   at Program.<Main>(String[] args)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

Přiznávám, že jsem ještě nepožádal o povolení přístupu dle těch instrukcí, ale i v takovém případě bych očekával nějakou human-readable chybu, ne `UnhandledException`, respektive nedokážu říct jestli ta exception s tím nějak souvisí.

**Comment by radeksimko** [comment]
Zvláštní je, že ten kontejner stále běží a ne-exitoval. Můžu zkusit přidat `-e debug=true` ale pokud chápu správně, tak to neovlivní logy co se posílají na STDOUT, resp. které sbírá Docker.

**Comment by schovi** [comment]
Mám stejnou chybu. `debug=true` nic nemění.
